default: &default
  # ==========================================
  # ===== Example Facebook Service Setup =====
  # ==========================================
  facebook:
    verify_token: <%= VERIFY_TOKEN %>
    page_access_token: <%= PAGE_ACCESS_TOKEN %>
    setup:
      greeting: # Greetings are broken up by locale
        - locale: default
          text: "Welcome to my Facebook Bot."
      get_started:
        payload: new_user
      persistent_menu:
        - locale: default
          composer_input_disabled: false
          call_to_actions:
          - type: payload
            text: Some Button
            payload: some_button
          - type: nested
            text: Developer Tools
            buttons:
              - type: payload
                text: Restart
                payload: developer->say_restart
              - type: payload
                text: Start test
                payload: developer->set_test

  #
  # ===========================================
  # ======== Example SMS Service Setup ========
  # ===========================================
  # twilio:
  #   account_sid: XXXTWILIO_ACCOUNT_SIDXXX
  #   auth_token: XXXTWILIO_AUTH_TOKENXXX
  #   from_phone: +14155330000

production:
  <<: *default
development:
  <<: *default
test:
  <<: *default
